version: "3.1"


services:
  postgres-moex-data-db:
    container_name: postgres-moex-data-db
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: ${MOEX_DATA_DB}
      POSTGRES_USER: ${MOEX_DATA_DB_USER}
      POSTGRES_PASSWORD: ${MOEX_DATA_DB_PASSWORD}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres-moex-data-db:/var/lib/postgresql/moex-data/data

  postgres-auth-service-db:
    container_name: postgres-auth-service-db
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: ${AUTH_SERVICE_DB}
      POSTGRES_USER: ${AUTH_SERVICE_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_SERVICE_DB_PASSWORD}
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - postgres-auth-service-db:/var/lib/postgresql/auth-service/data

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-net

  redis-cache:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-cache:/var/lib/redis/data

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - kafka-net

volumes:
  postgres-auth-service-db:
  postgres-moex-data-db:
  redis-cache:

networks:
  kafka-net:
    driver: bridge