CREATE TABLE IF NOT EXISTS user_credentials
(
    id       INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    uuid     UUID UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS securities
(
    id        INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    pair_code VARCHAR(7) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS user_actions
(
    id          INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    action_type VARCHAR(100) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE IF NOT EXISTS user_history
(
    id             INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id        INT UNIQUE NOT NULL,
    date           DATE       NOT NULL,
    time           TIME       NOT NULL,
    user_action_id INT        NOT NULL,
    FOREIGN KEY (user_action_id) REFERENCES user_actions (id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES user_credentials (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS user_security
(
    user_id     INT,
    security_id INT,
    FOREIGN KEY (user_id) REFERENCES user_credentials (id) ON DELETE CASCADE,
    FOREIGN KEY (security_id) REFERENCES securities (id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, security_id)
)