server:
  port: 0

spring:
  application:
    name: authentication-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: moex-data.currencies-1

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/master.yml
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true

        jdbc:
          batch_size: 110
        generate_statistics: true
        order_updates: true

kafka:
  topic: quotation.moex-data.currencies