server:
  port: 8080

spring:
  application:
    name: quotation-data-aggregator-service

  kafka:
    bootstrap-servers: localhost:9092

  cloud:
    openfeign:
      client:
        config:
          moex-client:
            url: https://iss.moex.com

kafka:
  retention: 14
  topic: "quotation.moex-data.currencies"


#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:${DISCOVERY_SERVICE_PORT}/eureka
#  instance:
#    instance-id: ${random.uuid}

management:
  endpoints.web.exposure.include: "prometheus, health"
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true

scheduler:
  currency-moex-client:
    cron-expression: "0 0 18 * * *"
    limit: 100
    securities:
      - "GBP"
      - "USD"
      - "EUR"
      - "CAD"
      - "CHF"
      - "KZT"
      - "JPY"
      - "CNY"
    meta-mode: "on"
    choice:
    string-order:


