server:
  port: 56782

eureka:
  client:
    service-url:
      defaultZone: http://localhost:${DISCOVERY_SERVICE_PORT}/eureka

spring:
  application:
    name: authentication-service

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/master.yml
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true

jwt:
  secret-key: ${JWT_SECRET}
  time-millis: 86400000

services:
  discovery-service-port: ${DISCOVERY_SERVICE_PORT}
  api-gateway-port: ${API_GATEWAY_PORT}
  config-service-port: ${CONFIG_SERVICE_PORT}

other:
  authentication:
    related_path: v1/authentication/