server:
  port: ${CONFIG_SERVICE_PORT}

spring:
  application:
    name: config-service

  profiles:
    active: git

  cloud:
    config:
      server:
        git:
          uri: ${GITHUB_URL}
          default-label: master
          search-paths: "{application}"

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL}